"""User migrations

Revision ID: 17c2d7bccfa4
Revises: 
Create Date: 2022-03-23 16:38:01.529382

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '17c2d7bccfa4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('legal_persons',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('cnpj', sa.String(), nullable=True),
    sa.Column('company_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_legal_persons_cnpj'), 'legal_persons', ['cnpj'], unique=True)
    op.create_table('natural_persons',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('cpf', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_natural_persons_cpf'), 'natural_persons', ['cpf'], unique=True)
    op.create_table('users',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('zip_code', sa.String(), nullable=True),
    sa.Column('district', sa.String(), nullable=True),
    sa.Column('street', sa.String(), nullable=True),
    sa.Column('number', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('legal_person_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('natural_person_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['legal_person_id'], ['legal_persons.id'], ),
    sa.ForeignKeyConstraint(['natural_person_id'], ['natural_persons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_natural_persons_cpf'), table_name='natural_persons')
    op.drop_table('natural_persons')
    op.drop_index(op.f('ix_legal_persons_cnpj'), table_name='legal_persons')
    op.drop_table('legal_persons')
    # ### end Alembic commands ###
