"""nullable fields

Revision ID: 20392f96a498
Revises: 17c2d7bccfa4
Create Date: 2022-03-23 16:48:09.055940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20392f96a498'
down_revision = '17c2d7bccfa4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
